### ISSUE TITLE
lukin

### ISSUE THREAD

**Issue by Mecamute** [jProgr/TokiPonaDictionary#1]
The word "lukin" is missing a definition. It also means "try to".

I've never used this website before, so I don't quite know what I'm doing. I hope I'm helping, at least a little bit.

Loved this dictionary... Keep up the good work!

**Comment by jProgr** [comment]
Thanks!

I based the dictionary in the contents of the book "Toki Pona: the language of good – the simple way of life" by B. J. Knight, in there the meaning "try to" is missing. Some of the words have evolved and some others have died. Maybe the meaning is old? Maybe new? The book is from 2005. Do you have a source?

**Comment by jProgr** [comment]
I researched more and found a 2019 version of the book with that meaning and a few new words that I didn't know about.

I will update the dictionary. Thanks!
