### ISSUE TITLE
ku words

### ISSUE THREAD

**Issue by mathmaster13** [jProgr/TokiPonaDictionary#27]
Hello,
New words just got added into toki pona (see (https://tokipona.org/)) and I was wondering if you could add at least the nimi ku suli into the dictionary. This dictionary has helped me a lot, so thank you!

**Comment by jProgr** [comment]
Oh, I did not know there was a new book available. If you are talking about that, I will see if I can get it in my country.

**Comment by mathmaster13** [comment]
Thank you, and thanks for making this great dictionary.
