### ISSUE TITLE
"Yes" gives no result

### ISSUE THREAD

**Issue by egils-consulting** [jProgr/TokiPonaDictionary#8]

**Comment by jProgr** [comment]
As noted in the official Toki Pona book under Part 1, Lesson 7: "To reply «yes», repeat the verb". There seems to be no "yes" in Toki Pona. Have you found a word for "yes" used in the community? Do you have a source?

**Comment by egils-consulting** [comment]
Oh, thanks. Could you add that then?

**Comment by jProgr** [comment]
I'm sorry, I'm a little lost. What should I add? A "yes" entry? How should I add it?

**Comment by egils-consulting** [comment]
I have no idea 😅 I think its valuable information to get when trying to learn via lookups in the dictionary, but perhaps its better placed somewhere else like in a short introduction to the language.
